### ISSUE TITLE
Migrate to Vite on Vue 3 with tailwind css 3.0

### ISSUE THREAD

**Issue by ProFireDev** [JCS-Computer-Science/project-module-1-project-flip#65]
see  issues #58  #54 and PR #64 

- figure out a way to update post css 8

**Comment by ProFireDev** [comment]
https://github.com/forsartis/vue-cli-plugin-tailwind/issues/32

**Comment by ProFireDev** [comment]
![image](https://user-images.githubusercontent.com/34112557/146518516-64df0660-f4a5-41b9-b858-42f07a080c14.png)

**Comment by ProFireDev** [comment]
https://forum.vuejs.org/t/vue-3-postcss-8/112492/5

**Comment by ProFireDev** [comment]
heres the logs preventing npm run serve from workig

![error log](https://user-images.githubusercontent.com/34112557/146598963-17be5285-b4e7-4167-97d2-0a53f1456142.png)

**Comment by ProFireDev** [comment]
steps to run though to get this working again - drop vue cli to move to postcss 8 and vite. this will install tailwind 2.0 and from there tailwind 3 support could come later

https://v2.tailwindcss.com/docs/guides/vue-3-vite

https://vitejs.dev/guide/#scaffolding-your-first-vite-project

**Comment by ProFireDev** [comment]
used

https://github.com/web2033/vite-vue3-tailwind-starter as a good starting point

**Comment by ProFireDev** [comment]
merge [vite-base](https://github.com/Aakansh-C/Project-Flip) into vite migration branch - see #73 for the original attempt at this

**Comment by ProFireDev** [comment]
Also this branch is worth checking out, I tried to incorporate PWA but had a hard time getting it fully working 

https://github.com/JCS-Computer-Science/project-module-1-project-flip/tree/Vite-migration

**Comment by ProFireDev** [comment]
fixed with #76, ready to fully implement Into Staging after the PWA, should be done tomorrow

**Comment by ProFireDev** [comment]
see issue #78 If you cant get the project to run properly locally

**Comment by ProFireDev** [comment]
PWA stuff:

https://vite-plugin-pwa.netlify.app/guide/#setup 

see 

> 
> https://github.com/JCS-Computer-Science/project-module-1-project-flip/tree/Vite-migration

**Comment by ProFireDev** [comment]
see https://github.com/JCS-Computer-Science/project-module-1-project-flip/tree/Deploy for the original PWA confif, then port that over to vite

**Comment by ProFireDev** [comment]
PWA is configured, current issues: 

![image](https://user-images.githubusercontent.com/34112557/149230959-bac1b3cd-34b1-4122-8632-da9d3d111129.png)

**Comment by ProFireDev** [comment]
reference https://github.com/antfu/vite-plugin-pwa

**Comment by ProFireDev** [comment]
final solution - port here
https://www.npmjs.com/package/create-vite-pwa

**Comment by ProFireDev** [comment]
```css
html::before {
content: ' ';
display: block;
background-image: url(background.jpg);
background-position: center center;
background-size: 100% 100%;
background-repeat: no-repeat;
height: 100vh;
width: 100vw;
top: 0;
bottom: 0;
left: 0;
right: 0;
position: fixed;
z-index: -10; // This is pretty important.
}
```
